apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moulin-server
  labels:
    app: moulin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: moulin
    spec:
      containers:
        - image: dhrp/moulin:v0.2
          name: server
          ports:
            - containerPort: 8042
          command: ["sh", "-c", "sleep 10 && /go/bin/moulin"]
        - image: redis
          name: redis

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: moulin
  name: moulin-service
spec:
  ports:
  - name: http
    port: 8042
    protocol: TCP
    targetPort: 8042
  selector:
    app: moulin
  sessionAffinity: None
  type: LoadBalancer
